Initialized joboffers app
PyAr/pyarweb pull request #487
Opened 2021-11-01 19:44 UTC by skalanux

Initialization of JobOffers app, and update of Test infrastructure

2021-11-22 12:50 UTC, facundobatista commented
Ojo que esto no funca:
```
ProgrammingError at /trabajo-nueva/admin/

relation "joboffers_joboffer" does not exist
LINE 1: ..."."slug", "joboffers_joboffer"."fields_hash" FROM "joboffers...
```

2021-11-24 20:21 UTC, facundobatista requested changes

2021-11-25 17:40 UTC, germanp commented on joboffers/models.py
> +    REMOTE = 'REM', _('Remoto')
OK, ya lo actualicé.

2021-11-30 11:55 UTC, facundobatista approved these changes
Great, thanks!

2021-11-30 11:55 UTC, merged