Happy path for Joboffer approval
PyAr/pyarweb pull request #496
Opened 2021-12-22 19:04 UTC by germanp

Con este pull request ya implementamos el camino feliz para aprobar una oferta, es decir, que el publicador la cree desde 0, la envíe a moderación y posteriormente un usuario admin la pueda aceptar. Para poder crear la oferta hay que crear un usuario y asociarlo a una compañía desde el admin agregando un UserCompanyProfile con la compañía.

2022-01-02 19:27 UTC, facundobatista requested changes
Hola! Anoté un par de detalles menores, pero me trabé con lo que es probar esto...

Parado en este branch, corrí las migraciones (`make migrate`), luego siendo admin me creeé un usuario `testfacu` y una compañía nueva... pero no encuentro en el admin cómo relacionar el usuario a esa compañía... 

Los "títulos" que tengo a la izquierda en el admin son:
```
Autenticación y autorización
Cuentas
Cuentas Sociales
Django Summernote
Events
Joboffers
Jobs
Jobs
News
Pycompanies
Sitios
Tagging
Taggit 
```

¿Me está faltando un paso?

2022-01-03 19:10 UTC, germanp commented
> Hola! Anoté un par de detalles menores, pero me trabé con lo que es probar esto...
> 
> Parado en este branch, corrí las migraciones (`make migrate`), luego siendo admin me creeé un usuario `testfacu` y una compañía nueva... pero no encuentro en el admin cómo relacionar el usuario a esa compañía...
> 
> Los "títulos" que tengo a la izquierda en el admin son:
> 
> ```
> Autenticación y autorización
> Cuentas
> Cuentas Sociales
> Django Summernote
> Events
> Joboffers
> Jobs
> Jobs
> News
> Pycompanies
> Sitios
> Tagging
> Taggit 
> ```
> 
> ¿Me está faltando un paso?

No, ahí me confundí yo, el admin está en la rama con los cambios para asociar usuarios con compañía. Podés asociar un usuario desde la shell.

```
$ make dockershell`
$ python manage.py shell_plus`
>>> usuario = User.objects.get(username='testfacu')`
>>> compania = Company.objects.first()
>>> UserCompanyProfile.objects.create(user=usuario, company=compania)
```

2022-01-03 19:49 UTC, germanp commented on joboffers/joboffer_actions.py
> +def register_action(func, profile):
Ahí lo agregué, ese solo faltaba al parecer. O me equivoco?

2022-01-03 19:50 UTC, germanp commented on joboffers/joboffer_actions.py
> +    roles = set([])
cambiado

2022-01-04 21:26 UTC, facundobatista commented
Genial, ahí pude entrar entonces a `http://0.0.0.0:8000/trabajo-nueva/nueva/`, con un usuario `testfacu` asociado a la compañia en cuestión.

Detalles que encontré a corregir:
1. ¿Por qué hay un combobox de Empresa? Si el usuario tiene que estar asociado siempre a una sola? Encima aparece la empresa del usuario y otra que creé... ahí falla algo.
2. "Tipo de contratación" y "Rango salarial" les falta "subtítulo"
3. Cargué una oferta de prueba y crasheó con
```
IntegrityError at /trabajo-nueva/nueva/
new row for relation "joboffers_joboffer" violates check constraint "joboffers_joboffer_location_not_null_when_not_remote"
DETAIL:  Failing row contains (1, titulo1, null, null, null, null, 1+, IN_OFFICE, EMPLOYEE, mucho, <p>desc1<br></p>, 2022-01-04 21:09:06.686356+00, 2022-01-04 21:09:06.686406+00, DEACTIVATED, titulo1, null, null, 2, 2).
```
4. Le cargué location, crasheó con:
```
IntegrityError at /trabajo-nueva/nueva/
new row for relation "joboffers_joboffer" violates check constraint "joboffers_joboffer_not_all_contact_info_null"
DETAIL:  Failing row contains (2, titulo1, wee, null, null, null, 1+, IN_OFFICE, EMPLOYEE, mucho, <p>desc1<br></p>, 2022-01-04 21:21:25.953658+00, 2022-01-04 21:21:25.95373+00, DEACTIVATED, titulo1, null, null, 2, 2).
```
5. le cargué un mail que era cualquiera, y entró; debería validar que el mail tenga el formato correcto
6. cargué una oferta sin empresa relacionada; mal

2022-01-05 15:16 UTC, germanp commented
> * ¿Por qué hay un combobox de Empresa? Si el usuario tiene que estar asociado siempre a una sola? Encima aparece la empresa del usuario y otra que creé... ahí falla algo.

Ese cambio lo tenemos en otra rama. La idea de esta rama es tener las transiciones de los estados de la oferta y los permisos. Quisimos encarar esto primero porque es transversal a todo el proyecto.



> * "Tipo de contratación" y "Rango salarial" les falta "subtítulo"

Bueno, le agrego una descripción mas larga.

2022-01-05 15:19 UTC, germanp commented
> 3\. Cargué una oferta de prueba y crasheó con

Si, la validación está en el modelo pero el form no la implementa, hay que hacerla manualmente. Igual remarco que la intención era que funcione el flujo de estados y no sobrecargar el PR con otras cosas y hacerlo mas largo.

2022-01-05 15:22 UTC, germanp commented
> * le cargué un mail que era cualquiera, y entró; debería validar que el mail tenga el formato correcto

Si, le falta el validador. Si querés lo incorporo en el mismo PR, pero habría que agregar el test.

2022-01-05 15:29 UTC, germanp commented
> 10\. cargué una oferta sin empresa relacionada; mal

Si, está definido como null=True, no si quedo así pensando en la migración, pero no tiene sentido. Si querés lo incorporo como parte de este PR. Decime.

2022-01-07 19:46 UTC, facundobatista approved these changes
Approving to unblock. Please annotate the remaining issues to be solved later.

2022-01-07 19:50 UTC, merged