User company admin
PyAr/pyarweb pull request #501
Opened 2022-01-10 21:03 UTC by IanPuchetti

Added a section in companies list to administrate the company that the user is associated, or search a company to request the association.

2022-01-15 14:29 UTC, facundobatista requested changes
Buenísimo!!! Anoté algunos detalles simples. Gracias!

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/views.py
> +            return redirect('/empresas/admin/')
Cada punto de la secuencia del if/elif y el except, todos hacen el mismo redirect.  Mover eso al final, una sola vez.

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/views.py
> +        return False
Acá devolver `None`, no `False`, que es lo que tiene sentido cuando algo no existe.

O sea, o devuelve el user_company, o "nada" (None), no "falso".

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/views.py
> +        except User.DoesNotExist:
Hay demasiado código adentro del `try`. En qué lugar puede levantarse esta excepción? si es en la linea 161, envolver sólo esa linea con el `try/except`.

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/views.py
> +        if (users_quantity == 1):
No hacen falta paréntesis acá.

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/views.py
> +            except UserCompanyProfile.DoesNotExist:
Acá pasa lo mismo que comenté en el otro código, tanto del "doble return" que no tiene sentido, y que el código dentro del `try` es demasiado.

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/views.py
> +                return context
Lo mismo que en los otros dos comments.

2022-01-15 14:29 UTC, facundobatista commented on pycompanies/urls.py
> +    re_path(r'^(?P<pk>\d+)/delete/$', CompanyDeleteView.as_view(), name='delete'),
Las URLs en general están en castellano, no mezclemos con inglés porque queda horrible.

2022-01-19 23:02 UTC, facundobatista requested changes
Segunda tanda con algunos detalles.

2022-01-19 23:02 UTC, facundobatista commented on pycompanies/urls.py
> +    re_path(r'^add/$', CompanyCreateView.as_view(), name='add'),
Quedó esta colgada en castellano...

2022-01-20 17:55 UTC, IanPuchetti commented on pycompanies/views.py
> +    return user_company or None
saqué el `or None`, ahora retorna directamente `UserCompanyProfile.objects.filter(user=user).first()`

2022-01-20 17:56 UTC, IanPuchetti commented on pycompanies/views.py
> +            user = user_queryset.first()
Si, ya está acomodado. Se me pasó acomodarlo como en otras partes del código.

2022-01-20 17:56 UTC, IanPuchetti commented on pycompanies/urls.py
> +    re_path(r'^add/$', CompanyCreateView.as_view(), name='add'),
Listo!

2022-01-21 23:08 UTC, facundobatista approved these changes
awesome!

2022-01-21 23:08 UTC, merged