Job publishing
PyAr/pyarweb pull request #517
Opened 2022-02-10 16:54 UTC by skalanux

- Este cambio contiene el publicador a facebook de joboffers . Tiene todos los tests unitarios, y adicionalmente dos comandos para poder probar el posteo a facebook. El formato del post no está del todo definido, tenemos pensado ajustarlo después. Solo implica modificar los templates para cada plataforma.
- Comando create_facebook_page_token, necesario para poder crear las claves y app facebook para publicar. Debería considerarse crear una página de facebook de prueba para poder testear con tranquilidad. Dentro del archivo se encuentra el procedimiento para obtener el token.
- Comando test_facebook. Luego de obtener los token, este comando permite, probar el simple posteo de un mensaje de prueba a facebook, asi como también un joboffer, para asegurar tanto que la conexión es correcta, como el formato esperado.

El publicador de Facebook, hereda de una clase base "Publisher" la cual tiene toda la mayor parte del comportamiento en la publicación, excepto la conexión con la API. Para las siguientes plataformas, sólo será necesario crear el template e implementar el método de publicación de la misma.

2022-02-10 22:27 UTC, facundobatista requested changes
Hola! Está muy bien la idea y estructura, ahí anoté algunos detalles. Gracias!!

2022-02-10 22:27 UTC, facundobatista commented on joboffers/publishers/facebook/__init__.py
> +        status = requests.codes.server_error
Esto es falso, la excepción puede ser error de conexión, timeout, etc... clavar un 500 ahí es misleading. Preferible dejarla en None.

2022-02-10 22:27 UTC, facundobatista commented on joboffers/publishers/facebook/__init__.py
> +        logging.error(ERROR_LOG_MESSAGE.format(FACEBOOK_POST_URL, payload, result_info))
No construyas a mano el mensaje de error, usá la infra de logging para eso (`logging.error(mensaje_template, param1, param2, ...)`)

2022-02-11 23:24 UTC, skalanux commented on joboffers/publishers/__init__.py
> +    def publish(cls, job_offer: 'JobOffer'):
Listo

2022-02-11 23:25 UTC, skalanux commented on joboffers/publishers/__init__.py
> +    @classmethod
Arreglado!, gracias por hacerlo notar, a veces uno empieza con una idea y al hacer refactor termina con algo que no tiene sentido

2022-02-11 23:26 UTC, skalanux commented on joboffers/publishers/facebook/__init__.py
> +        logging.error(ERROR_LOG_MESSAGE.format(FACEBOOK_POST_URL, payload, result_info))
Cambiado.

2022-02-20 11:33 UTC, tzulberti approved these changes

2022-02-20 15:14 UTC, facundobatista approved these changes
Buenísimo!

2022-02-21 13:20 UTC, merged