Joboffer default company
PyAr/pyarweb pull request #519
Opened 2022-02-11 19:46 UTC by IanPuchetti

## Temas tratados:

- Al enviar el formulario, la compañía se manda vacía y da error

## Pruebas realizadas:

- Tests funcionando correctamente
- Pep8 ok

## Cómo probar los cambios:

1. Ingresar a /trabajo-nueva/nueva/
2. Rellenar el formulario y enviarlo
3. Debería crear la nueva oferta correctamente

Gracias por contribuir con el proyecto.

Estamos pendiente de revisar los cambios propuestos.

2022-02-11 22:41 UTC, facundobatista requested changes
Muy pequeño detalle! Acordate de actualizar master.

2022-02-11 22:41 UTC, facundobatista commented on pycompanies/views.py
> +            user_company = user_company = UserCompanyProfile.objects.for_user(user)
Te quedó repetido el `user_company =`

2022-02-20 11:58 UTC, tzulberti approved these changes

2022-02-20 15:20 UTC, facundobatista approved these changes
+1, gracias!

2022-02-21 19:38 UTC, merged