Twitter publishing
PyAr/pyarweb pull request #523
Opened 2022-02-22 20:07 UTC by skalanux

Este es el publisher para twitter. Para hacerlo funcionar, va a requerir crear una prueba/credenciales para twitter. Para correr los tests unitarios no es necesario, Pero si si se quiere correr el comando que lo testea "test_twitter". Como detalle, se unificó el comando para testear las publicaciones y comparten la base con el de facebook.

2022-02-25 20:56 UTC, facundobatista requested changes
Buenísimo!! Ahí anoté un detalle.

2022-02-25 20:56 UTC, facundobatista commented on joboffers/publishers/twitter/__init__.py
> +            logging.error(ERROR_LOG_MESSAGE_AUTH, _repr_credentials(), err)
Sé que complica el debugging... pero NUNCA logueemos credenciales.

2022-02-25 20:56 UTC, facundobatista commented on joboffers/publishers/twitter/__init__.py
> +            status = None
No hace falta esta linea, hacer `return` directamente dos lineas abajo es suficiente.

2022-03-03 23:48 UTC, skalanux commented on joboffers/publishers/twitter/__init__.py
> +            logging.error(ERROR_LOG_MESSAGE_AUTH, _repr_credentials(), err)
Si, estoy de acuerdo, la verdad que dude en ponerlas, pero me encontré con el problema de que no me funcionaba y despues de probar un rato, tuve que entrar al container y mirar las variables de entorno para darme cuenta de un pequeño error sobre como estaban siendo parseadas, para llegar a ese error tuve que tener acceso a las claves tal cual las estaba viendo el programa. Estarias de acuerdo en ofuscar las credenciales y mostrar solo primera y últimas letras o preferís directamente ocultar esta información?

2022-03-04 00:09 UTC, skalanux commented on joboffers/publishers/twitter/__init__.py
> +            status = None
Listo, cambiado esto, fue por puro Toc :)

2022-03-04 22:24 UTC, facundobatista commented on joboffers/publishers/twitter/__init__.py
> +            logging.error(ERROR_LOG_MESSAGE_AUTH, _repr_credentials(), err)
¿y si las hasheamos?

Onda loguear el sha256 de la credencial...

2022-03-04 22:25 UTC, facundobatista commented on joboffers/publishers/twitter/__init__.py
> +            logging.error(ERROR_LOG_MESSAGE_AUTH, _repr_credentials(), err)
Eso evitaría loguear la credencial en sí, pero podés validar si se está usando lo que pensás que se está usando...

2022-03-07 18:38 UTC, skalanux commented on joboffers/publishers/twitter/__init__.py
> +            logging.error(ERROR_LOG_MESSAGE_AUTH, _repr_credentials(), err)
Listo, lo cambié para que haga eso

2022-03-11 19:19 UTC, facundobatista approved these changes
+1, buenísimo!

2022-03-11 19:19 UTC, merged