Implementa la posibilidad de rectificar la moderacion para el usuario que la hizo.
PyAr/pyarweb pull request #527
Opened 2022-03-11 22:09 UTC by germanp

## Cambios propuestos:

-  
-  

## Temas tratados:

- Closes

## Pruebas realizadas:

- 
- 

## Cómo probar los cambios:

1.
2.
3.

Gracias por contribuir con el proyecto.

Estamos pendiente de revisar los cambios propuestos.

2022-03-16 13:42 UTC, facundobatista requested changes
Hola! Anoté algunos detalles... gracias!

2022-03-16 13:42 UTC, facundobatista commented on joboffers/joboffer_actions.py
> +    Retrieves a list of the roles marching the given user and company.
"marching"?

2022-03-16 13:42 UTC, facundobatista commented on joboffers/constants.py
> +        'icon_class': 'glyphicon-arrow-up',
¿No deberían todos tener "title"?

2022-03-16 13:42 UTC, facundobatista commented on joboffers/joboffer_actions.py
> +        # ^ Checks that the user is publisher in the given company
el comentario va antes del código (te ahorra la flechita para arriba :) )

2022-03-16 13:42 UTC, facundobatista commented on joboffers/tests/test_joboffer_actions.py
> +#
¿vacio?

2022-03-16 13:42 UTC, facundobatista commented on joboffers/templates/joboffers/joboffer_admin.html
> +        <p>{% trans 'No se encotraron ofertas.' %}</p>
"encontraron"

2022-03-16 13:53 UTC, facundobatista commented on joboffers/constants.py
> +        'icon_class': 'glyphicon-arrow-up',
ok

2022-03-16 13:53 UTC, facundobatista commented on joboffers/joboffer_actions.py
> +        # ^ Checks that the user is publisher in the given company
ack

2022-03-16 13:53 UTC, facundobatista commented on joboffers/tests/test_joboffer_actions.py
> +#
es un comentario vacio, ¿para qué?

2022-03-17 13:58 UTC, germanp commented on joboffers/tests/test_joboffer_actions.py
> +#
Es para marcar el final de los fixtures de pytest

2022-03-17 18:36 UTC, germanp commented on joboffers/joboffer_actions.py
> +        # ^ Checks that the user is publisher in the given company
cambiado

2022-03-17 18:36 UTC, germanp commented on joboffers/templates/joboffers/joboffer_admin.html
> +        <p>{% trans 'No se encotraron ofertas.' %}</p>
cambiado

2022-03-17 18:37 UTC, germanp commented on joboffers/joboffer_actions.py
> +    Retrieves a list of the roles marching the given user and company.
cambiado

2022-04-05 11:54 UTC, facundobatista approved these changes
Buenísimo, gracias!

2022-04-06 15:06 UTC, merged