Discourse publishing
PyAr/pyarweb pull request #530
Opened 2022-04-11 17:56 UTC by skalanux

Les paso el PR para poder publicar a Discourse. En particular este publicador agrega al titulo como parámetro, dado que es la única fuente de publicación que requiere de un título (al menos único). Discuourse es bastante exquisito, como manera de asegurar unicidad y desalentar el spam, en cuanto al tamaño del titulo, de no repetirse, por lo que fue necesario hacer algunos ajustes. Otra cosa que tuve que agregar en el requirements, es la versión de Bleach pineada, debido a que hay un issue en un release que hicieron hace poco [0] que lo está haciendo fallar.

[0]: https://github.com/marksweb/django-bleach/issues/51

2022-04-11 20:47 UTC, facundobatista requested changes
Buenísimo!!! Ahí anoté un par de cosas, gracias!

2022-04-11 20:47 UTC, facundobatista commented on joboffers/management/commands/__init__.py
> +                    'Hubo un error al querer publicar la oferta en: '
Las dos lineas pueden ser una.

2022-04-11 20:47 UTC, facundobatista commented on joboffers/management/commands/__init__.py
> +                    'Oferta publicada con éxito en: ' f'{publisher.name}.'
Te quedaron dos strings separados.

2022-04-11 20:47 UTC, facundobatista commented on joboffers/publishers/discourse/__init__.py
> +        assert len(post_title) >= MIN_LENGTH_POST_TITLE
Esto termina explotando en el servidor y es un embole. Considerá el caso y rellenalo de algo único. Onda...
```
>>> import uuid
>>> post_title = "Re corto"
>>> if len(post_title) < 20:
...   post_title = f"{post_title} ... {uuid.uuid4()}"[:20]
...
>>> post_title
'Re corto ... fcf80a3'
```

2022-04-11 20:47 UTC, facundobatista commented on pyarweb/settings/base.py
> +STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
Es más legible (y tiene más sentido) si es una lista, no una tupla...

2022-04-11 20:47 UTC, facundobatista commented on pyarweb/settings/base.py
> +        ),
¿Por qué este cambio?

2022-04-11 20:47 UTC, facundobatista commented on requirements.txt
> +bleach==4.1.0
Si no usamos `bleach` directamente, y lo ponemos acá para pinnearlo porque sino no anda, agregá al menos un comentario indicando con qué versiones no anda, etc. Toda la info necesaria para que en dos años no estemos dos semanas investigando por qué esta dependencia acá...

2022-04-12 00:25 UTC, skalanux commented on joboffers/publishers/discourse/__init__.py
> +        assert len(post_title) >= MIN_LENGTH_POST_TITLE
Si, por mi tambien me parece poner algo asi o al menos no la fecha solamente, es lo que te había mencionado por chat en su momento

2022-04-12 11:58 UTC, skalanux commented
Aclaro en general antes que nada, que la mayoría de los cambios, es porque, arranqué con un proyecto y estamos usando black, por lo se coló la formateada por convención. Recuerdo que en este proyecto no lo ibamos a usar, asi que my bad, lo cambio enseguida. Luego te dejo algunos comentarios en algún issue.

2022-04-12 12:06 UTC, skalanux commented on pyarweb/settings/base.py
> +STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
Esto es tema del format  ya estaba de antes asi. Lo cambio a Lista.

2022-04-12 13:59 UTC, skalanux commented on joboffers/publishers/discourse/__init__.py
> +        assert len(post_title) >= MIN_LENGTH_POST_TITLE
Hay un tema acá también que es el que el título debe tener cierta unicidad, por el cual también le habíamos agregado la fecha. Y la Fecha + un uuid (en caso de que no llegue a los 20 caracteres queda raro). Actualmente el assert esta casi como último salvavidas, ya que el campo de título tiene puesto un mínimo de 20 caracteres para evitar tener que enchastrarlo tanto, y de todos modos este error se deberia agarrar mas arriba. Si vamos a poner un uuid, estaría bueno quizas sacar la fecha y que todos tengan ese uuid. Me gustaría saber tu opinión con respecto a esto, antes de implementar algo mas.

2022-04-14 12:52 UTC, facundobatista commented on joboffers/publishers/discourse/__init__.py
> +        assert len(post_title) >= MIN_LENGTH_POST_TITLE
Entiendo lo del corner case, pero si podemos evitar que el servidor explote, mejor. Prefiero que quede feo :p.

Ahora recuerdo lo de la fecha que habíamos hablado, es verdad! Sí, metamos un UUID y ya... que igual se trunca al mínimo necesario...

Gracias!

2022-04-18 17:54 UTC, skalanux commented on requirements.txt
> +bleach==4.1.0
Listo

2022-04-18 17:54 UTC, skalanux commented on joboffers/publishers/discourse/__init__.py
> +        assert len(post_title) >= MIN_LENGTH_POST_TITLE
Listo

2022-04-20 22:46 UTC, facundobatista approved these changes
Buenísimo, gracias!

2022-04-20 22:46 UTC, merged