Notificaciones por mail
PyAr/pyarweb pull request #535
Opened 2022-04-27 21:13 UTC by germanp

Este PR tiene las notificaciones por mail que se le envían a los publicadores de oferta cuando se aprueba/rechaza la oferta y el comando que caduca las ofertas viejas y también notifica a los publicadores

2022-04-29 18:32 UTC, germanp commented on joboffers/views.py
> +        publishers_addresses = offer.get_publisher_mail_addresses()
Me autocomento. Acá tendría que haber usado send_mail_to_publishers() que es la función que extraje pero me olvidé de reemplazarla acá.

Agrego un commit mas para arreglarlo

2022-05-06 09:50 UTC, facundobatista requested changes
Buenísimo!!! Ahí anoté algunos detalles, avisame cualquier cosa. Gracias!

2022-05-06 09:50 UTC, facundobatista commented on joboffers/models.py
> +        It filters user the empty mail field
Quedó raro este docstring.

2022-05-06 09:50 UTC, facundobatista commented on joboffers/models.py
> +        Get the visualizations amount for the given event type
s/amount/count/ en docstring y nombre del método.

2022-05-06 09:50 UTC, facundobatista commented on joboffers/utils.py
> +        subject = EXPIRED_OFFER_MAIL_SUBJECT % {'title': joboffer.title}
No uses "old style" acá (y en los otros reemplazos), usá `.format()`

2022-05-06 09:50 UTC, facundobatista commented on joboffers/views.py
> +          APPROVED_MAIL_BODY % {'title': offer.title},
`.format()`

2022-05-06 09:50 UTC, facundobatista commented on joboffers/utils.py
> +          'contact_info_views': joboffer.get_visualizations_amount(EventType.CONTACT_INFO_VIEW),
Si siempre vamos a juntar esta info, entonces tenemos que mejorar `get_visualizations_amount`. No tiene sentido ir a la base de dato tres veces si siempre queremos lo mismo.

Ver arriba comentario en la función.

2022-05-06 09:50 UTC, facundobatista commented on joboffers/models.py
> +        return JobOfferAccessLog.objects.filter(joboffer=self, event_type=event_type).count()
En función de cómo se usa abajo, no hay que filtrar acá, sino devolver un diccionario con toda la info. Ej:

```
{
  EventType.LISTING_VIEW: 34,
  ...,
}
```

2022-05-06 09:50 UTC, facundobatista commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
Armar una sola cadena con múltiples `\n` es super error prone.

Una alternativa sencilla es usar `"""` y armar cadenas multilineas. Otra solución más limpia es usar "archivos de template", pero creo que en este caso donde los textos son cortos, con usar `"""` alcanza...

2022-05-09 21:30 UTC, germanp commented on joboffers/utils.py
> +          'contact_info_views': joboffer.get_visualizations_amount(EventType.CONTACT_INFO_VIEW),
La idea de ir a la base de datos para que los registros (teniendo en cuenta que van a ser muchísimos registros) los cuente la base sin tener que traérmelos todos en memoria y contarlos con python

2022-05-09 21:36 UTC, germanp commented on joboffers/models.py
> +        return JobOfferAccessLog.objects.filter(joboffer=self, event_type=event_type).count()
Los valores del enum EventType son valores enteros, llamarlo así me pareció mas entendible. Sino tendría que traer el diccionario ese y renombrarlo para poder renderear usando las variables con nombre.

2022-05-09 21:54 UTC, germanp commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
Es que así no puedo respetar las 100 columnas.

2022-05-09 21:55 UTC, germanp commented on joboffers/utils.py
> +        subject = EXPIRED_OFFER_MAIL_SUBJECT % {'title': joboffer.title}
Ok, ya lo cambié. Había entendido que era el default para gettext (supongo que por lasa herramientas de traduccion) ya que está así en los ejemplos de la documentación de django.

2022-05-10 12:52 UTC, germanp commented on joboffers/models.py
> +        It filters user the empty mail field
Arreglado

2022-05-10 12:52 UTC, germanp commented on joboffers/models.py
> +        Get the visualizations amount for the given event type
Cambiado

2022-05-10 12:52 UTC, germanp commented on joboffers/views.py
> +          APPROVED_MAIL_BODY % {'title': offer.title},
Cambiado

2022-05-16 17:33 UTC, facundobatista commented on joboffers/utils.py
> +          'contact_info_views': joboffer.get_visualizations_amount(EventType.CONTACT_INFO_VIEW),
Claro. Tenés que ir a la base de datos y traer los resultados, no todos los registros. Pero ir una sola vez, no tiene sentido ir N veces cuando ya sabés toda la info que necesitás.

2022-05-16 17:36 UTC, facundobatista commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
No entiendo. Por ejemplo acá, no me paso:

```
EXPIRED_OFFER_MAIL_BODY = _("""
Le informamos que la oferta "{title}" ha caducado. 

Han pasado los {expiration_days} días desde su última activación. Puede reactivar la oferta 
dirigiéndose a {offer_url}

Resumen de Visitas
==================
 - {listing_views} Visualizaciones en listado
 - {detail_views} Visualizaciones de la oferta completa
 - {contact_info_views} Visualizaciones de los datos de contacto.
""")
```

2022-05-16 17:38 UTC, facundobatista commented on joboffers/models.py
> +        return JobOfferAccessLog.objects.filter(joboffer=self, event_type=event_type).count()
Este comentario no lo entendí...

2022-05-16 17:40 UTC, facundobatista commented on joboffers/utils.py
> +          'contact_info_views': joboffer.get_visualizations_amount(EventType.CONTACT_INFO_VIEW),
Si no entiendo mal sería algo como esto: (ojo, no lo probé):

    JobOfferAccessLog.objects.filter(joboffer=self).values('event_type').annotate(total=Count('event_type')).all()

2022-05-16 18:49 UTC, germanp commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
Claro, pero acá estás agregando un salto de línea en la cuarta línea, después de "Puede reactivar la oferta" cuando en realidad es el mismo párrafo.

2022-05-16 19:35 UTC, germanp commented on joboffers/utils.py
> +          'contact_info_views': joboffer.get_visualizations_amount(EventType.CONTACT_INFO_VIEW),
> JobOfferAccessLog.objects.filter(joboffer=self).values('event_type').annotate(total=Count('event_type')).all()

Agregándole .sort_by() al final anda. Ahora me falta transformar los datos para poder usarlos.

2022-05-16 20:22 UTC, facundobatista commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
Sí! Es mejor controlar el layout del texto que tirar lineas largas que quizás después se vean feo en algún cliente...

2022-05-16 21:32 UTC, germanp commented on joboffers/utils.py
> +          'contact_info_views': joboffer.get_visualizations_amount(EventType.CONTACT_INFO_VIEW),
Cambiado

2022-05-16 21:39 UTC, germanp commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
Cambiado.

2022-05-17 14:14 UTC, facundobatista commented on joboffers/constants.py
> +EXPIRED_OFFER_MAIL_BODY = _(
También cambiá los otros templates! Que no tengan `\n` en el medio, e idealmente que ya estén wrapeados (no mandes una linea laaaaaaaaaaaarga sobre la cual no tenemos control de "estilo")

2022-05-17 14:16 UTC, facundobatista approved these changes
Genial, gracias!!

2022-05-17 19:43 UTC, merged