Envío a redes sociales y notificaciones a telegram
PyAr/pyarweb pull request #536
Opened 2022-05-05 20:24 UTC by germanp

En este PR agregamos el envío de la oferta a redes sociales, las notifcaciones a telegram para los moderadores y los comandos para caducar las ofertas de trabajo y notificar ofertas pendientes de moderación.

2022-05-23 20:42 UTC, facundobatista requested changes
Hola! Ahí anoté unos detalles pequeños, gracias!

2022-05-23 20:42 UTC, facundobatista commented on joboffers/management/commands/notify_pending_moderation_offers.py
> +    Mark old job offers as EXPIRED and send a mail to the publishers
este docstring quedó viejo? esta función no marca expiradas...

2022-05-23 20:42 UTC, facundobatista commented on joboffers/management/commands/notify_pending_moderation_offers.py
> +      'Check for pending moderation offers and send a telegram notifaction to the moderators group'
"notification"

2022-05-23 20:42 UTC, facundobatista commented on joboffers/management/commands/notify_pending_moderation_offers.py
> +            _('Se enviaron %(offers_notified)s recordatorios de moderación.') % {
Usá `.format`.

2022-05-23 20:42 UTC, facundobatista commented on joboffers/utils.py
> +            logging.error(e)
¿Por qué este cambio? Si tenemos un problema en el mail y no manda nada, ¿en qué log vemos el problema? ¿cómo nos damos cuenta?

2022-06-01 14:57 UTC, germanp commented on joboffers/management/commands/notify_pending_moderation_offers.py
> +            _('Se enviaron %(offers_notified)s recordatorios de moderación.') % {
Ahí lo cambié

2022-06-01 14:57 UTC, germanp commented on joboffers/management/commands/notify_pending_moderation_offers.py
> +      'Check for pending moderation offers and send a telegram notifaction to the moderators group'
Arreglado

2022-06-01 23:12 UTC, facundobatista approved these changes
Joyaaaa

2022-06-01 23:12 UTC, merged