Fix migration reference
PyAr/pyarweb pull request #568
Opened 2023-04-25 22:10 UTC by tzulberti

## Cambios propuestos:

-  
-  

## Temas tratados:

- Closes

## Pruebas realizadas:

- 
- 

## Cómo probar los cambios:

1.
2.
3.

Gracias por contribuir con el proyecto.

Estamos pendiente de revisar los cambios propuestos.

2023-04-26 13:53 UTC, facundobatista requested changes
No es cuestión sólo de cambiar el pycompanies/0005 a pycompanies/0006, hay otro problema, que es que justamente esa migración dice depender de `0005_remove_company_owner`, pero:

- la migración 0005 borra el atributo `owner`
- la migración 0006 crea `UserCompanyProfile`s usando ese `owner` que ya no está

2023-05-01 08:10 UTC, tzulberti commented
Tenias razon. Ahi arregle el orden de las migraciones para que siga el mismo orden que produccion:

```
web_production=# SELECT * FROM django_migrations WHERE app = 'pycompanies';
 id  |     app     |                   name                   |            applied
-----+-------------+------------------------------------------+-------------------------------
  86 | pycompanies | 0001_initial                             | 2017-03-26 01:40:58.849786+00
 116 | pycompanies | 0002_company_rank                        | 2018-06-02 22:29:30.81656+00
 150 | pycompanies | 0003_usercompanyprofile                  | 2022-06-16 13:06:45.700131+00
 161 | pycompanies | 0004_alter_usercompanyprofile_user       | 2022-10-15 13:53:51.816693+00
 162 | pycompanies | 0005_company_owner_to_usercompanyprofile | 2022-10-15 13:53:51.876139+00
 173 | pycompanies | 0006_remove_company_owner.py             | 2022-10-15 13:53:53.812139+00
(6 rows)
```

2023-05-01 20:45 UTC, facundobatista requested changes

2023-05-01 20:45 UTC, facundobatista commented on joboffers/migrations/0015_alter_joboffer_company.py
> +        ('pycompanies', '0006_company_owner_to_usercompanyprofile'),
Si no entiendo mal, este lo pasás a 0006 pero abajo lo renombrás a 005? O sea, luego de aplicar el parche ya no existe '0006_company_owner_to_usercompanyprofile'...

2023-05-18 11:48 UTC, facundobatista approved these changes
Maravilloso, muchas gracias!!

2023-05-18 11:49 UTC, merged