Fix 403 Error Page Aesthetics and Ensure Consistent URL Generation
PyAr/pyarweb pull request #592
Opened 2024-12-17 03:44 UTC by JigyasuRajput

## Cambios propuestos:

-  Fixed the 403 error page to match the site's aesthetics.
-  Ensured consistent URL generation and validation in the code.

## Temas tratados:

- Closes #567 

## Pruebas realizadas:

- Ran the tests successfully with no errors.
- Tested on Ubuntu 20.04

## Cómo probar los cambios:

1. Join a company on the site.
2. Manually visit the URL https://www.python.org.ar/empresas/agregar/ to confirm the 403 page is displayed with the updated aesthetics.

![image](https://github.com/user-attachments/assets/3c1020db-d993-4ffc-9425-768220ee8586)

Gracias por contribuir con el proyecto.

Estamos pendiente de revisar los cambios propuestos.

2024-12-24 21:55 UTC, facundobatista requested changes
It looks there are changes here that are also in other proposed PR?

Also please double check changes, there are some that are not really changing anything useful, thanks!

2025-01-04 20:05 UTC, eduzen requested changes

2025-01-04 20:16 UTC, JigyasuRajput commented on joboffers/views.py
> +        if (search):
Hello @eduzen,
I’ve reviewed your feedback and reverted the unnecessary changes in the PR. The updates now focus solely on fixing the issue with the 403 error page aesthetics.

Please let me know if there’s anything else that needs adjustment or improvement. I appreciate your guidance and time

Thank you!

2025-01-20 20:10 UTC, eduzen commented
It looks fine I think.

2025-01-20 20:10 UTC, eduzen approved these changes

2025-01-20 22:42 UTC, facundobatista approved these changes
+1

2025-01-22 23:08 UTC, merged